### ISSUE TITLE
How to create groups on the nodes?

### ISSUE THREAD

**Issue by claflico** [camptocamp/puppet-accounts#10]
How do we create actual groups on the nodes and add users to the groups? I see create_resources(group, $groups) here https://github.com/camptocamp/puppet-accounts/blob/9228311945f769dc2c7ded3b364984cdc0cee615/manifests/init.pp#L15 but don't see that it is actually defined in any other manifest.

**Comment by mcanevet** [comment]
@claflico you should pass a hash of `group` resources to the declaration of the `accounts` class (either using hiera or not)
