### ISSUE TITLE
strformat function breaks with Puppet 5.5.7

### ISSUE THREAD

**Issue by seidler2547** [camptocamp/puppet-accounts#63]
According to https://tickets.puppetlabs.com/browse/PUP-9268 the `strformat` function must be defined differently. Right now, if the server runs 5.5.7 and authorized keys are defined, then no clients will be able  to fetch a catalog.

**Comment by seidler2547** [comment]
I have no clue about Ruby programming, but the software engineer in me says #64  is probably functionally equivalent (and saves one gsub call in the input does not contain `%`).

**Comment by raphink** [comment]
Yes, I agree #64 fixes that.
