### ISSUE TITLE
Cannot find hiera accounts data

### ISSUE THREAD

**Issue by gtmtech** [camptocamp/puppet-accounts#7]
When using account::account, because it is a define(), it tried to look up usergroups in ::accounts::usergroups.

Within a define(), %{calling_module}, %{calling_class} etc. doesn't seem to be set, restricting the files which hiera will consider in-scope.

As such you have to put the hiera data in a directly referenced file rather than nicely comparmentalised in accounts.yaml

E.g.
suppose hiera.yaml is:

```
:hierarchy:
  - hiera/common/%{calling_module}
  - hiera/common/defaults
```

Then hiera should look up hiera/common/accounts.yaml for these values - but it doesn't because the code is within a define() instead. Hence you have to put it in hiera/common/defaults.yaml (in the example above).

**Comment by raphink** [comment]
How about retrieving the values in a wrapping class (a profile) and using that class name in hiera instead?

**Comment by gtmtech** [comment]
Just an update - the docs for this module say to use:

```
accounts::account { .... }
```

but in fact this does not work with hiera - however this:

```
class { "accounts":
  accounts => hiera_hash("accounts::accounts")
}
```

will work instead as class accounts calls create_resources on this accounts, and the hiera lookup operates outside where you have full control (because you can wrap this within a module or class, and use %{calling_class} within hiera.yaml.

Hope this helps anyone coming across this, the docs maybe could do with an update to point you to use the right method, rather than a combination of hiera and calling defines ?

**Comment by mcanevet** [comment]
@gtmtech I'm not sure to understand...
Please propose a PR and I'll see what I can do.
