### ISSUE TITLE
The module is incompatible with Puppet stdlib newer than 8.5.0

### ISSUE THREAD

**Issue by djmills64** [camptocamp/puppet-accounts#73]
We have had to fix our systems to release 8.5.0 of stdlib.
Would it be possible to release a new version of the module that supports the latest stdlib?

**Comment by JGodin-C2C** [comment]
Hello @djmills64,
The latest release does support puppet::stdlib from 9.4.0 as stated in the [metadata.json ](https://github.com/camptocamp/puppet-accounts/blob/master/metadata.json#L13)

**Comment by JGodin-C2C** [comment]
https://github.com/camptocamp/puppet-accounts/issues/74
