### ISSUE TITLE
Issue with release 2.1.0 and StdLib v9.4.1

### ISSUE THREAD

**Issue by djmills64** [camptocamp/puppet-accounts#74]
2.1.0 works with StdLib 8.5.0. But with 9.4.1 gets the error:
`<13>Nov 10 12:47:50 puppet-agent[15249]: Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown function: 'validate_hash'. (file: /etc/puppetlabs/code/environments/production/modules/accounts/manifests/authorized_key.pp, line: 16, column: 3) (file: /etc/puppetlabs/code/environments/production/modules/accounts/manifests/account.pp, line: 122) on node 4101_test_l3
`

**Comment by JGodin-C2C** [comment]
Hello djmills64, 
Please use the previously opened issue.

**Comment by JGodin-C2C** [comment]
I see , ok, i will double-check the validate functions.

**Comment by JGodin-C2C** [comment]
Fixed by a0a8419

**Comment by djmills64** [comment]
Thanks, 2.1.1 works with StdLib 9.4.1
